### ISSUE TITLE
Ruffles transport: client can't connect

### ISSUE THREAD

**Issue by dosomder** [MidLevel/Ruffles#2]
**Describe the bug**
Client can not connect to a host using Ruffles Transport. Error message is "Connection not alive". Firewall on host is disabled, `netstat` shows port is being listened

**To Reproduce**
Simple project using Ruffles transport

**Expected behavior**
Client connects successfully

**Environment (please complete the following information):**

OS: Windows 10 & Oculus Quest (Android)
Unity Version: 2019.1.6f1
MLAPI Version: 10.13.0
Ruffles: No version shown in Unity, Ruffles.dll says 1.0.0

**Comment by TwoTenPvP** [comment]
This appears to be a Ruffles issue. Connections from Linux to Linux work fine. Android connection to Linux server does not work and I get the same results as you.

**Comment by dosomder** [comment]
Did you already have a chance to look into this?

**Comment by TwoTenPvP** [comment]
Nope, will check this asap. Sorry about the delay. MLAPI has been my main focus.

**Comment by TwoTenPvP** [comment]
Should be fixed in the latest version. It will be updated to NuGet and to the MLAPI Transport shortly.

**Comment by dosomder** [comment]
Thanks a lot, that's great. I will test it soon

**Comment by dosomder** [comment]
The final issue for me was that the time on the client and server did not match! Seems UNET does not care about time but Ruffles does. So make sure the time is the same.

**Comment by TwoTenPvP** [comment]
The time thing is a security feature on Ruffles. It can be turned off.

**Comment by dosomder** [comment]
Sure I understand that. Would be good if it was documented though. Or if the error message was visible on Android 👍

**Comment by TwoTenPvP** [comment]
Right, maybe even implement NTP.

Ruffles is WIP. I want to add fragmentation before docs.
