### ISSUE TITLE
Simulating latency not working.

### ISSUE THREAD

**Issue by ghost** [MidLevel/Ruffles#20]
**Describe the bug**
Using the simulator in MLAPI and ruffles as a transport. 
Setting latency to 1800-2000ms has no effect and latency is still 0ms.
**To Reproduce**
1. Create MLAPI project
2. Use ruffles
3. Enable Simulator with latency
4. Test latency
5. 0 ms

**Expected behavior**

There should be a delay of 1800-2000ms.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2019.1
 - Ruffles Version: LTS from MLAPI installer

**Comment by TwoTenPvP** [comment]
Found the problem, it's in the time code.
