### ISSUE TITLE
Is this part of the Readme as it should be?

### ISSUE THREAD

**Issue by furkangkhsn** [MidLevel/Ruffles#42]
![ReliableOrderedReadme](https://github.com/MidLevel/Ruffles/assets/23143160/083cbac6-edde-4941-833f-cf0279553a11)
The readme part of the ReliableOrdered said "Message delivery is not guarenteed. It is a reliable channel. Shouldn't it be reliable?

**Comment by TwoTenPvP** [comment]
Yes it's correct.

You are guaranteed to get at least one of the messages.
If you want to change a light bulbs color for example, this is a good channel to use.
If you change it twice in quick succession, we only send the latest and most up to date change.
